---
# provisioning-production.yml

- name: deployment | frontend applications
  hosts: "car-details-server"
  gather_facts: "false"
  tasks:
    - name: Create application container
      docker_container:
        name: car-details-service
        image: 409506722486.dkr.ecr.ap-southeast-1.amazonaws.com/car-details-service
        env:
          PORT: 80
          DS_URL: jdbc:postgresql://postgres:5432/cars
          DS_USERNAME: cars
          DS_PASSWWORD: carscars
          DS_DRIVER: org.postgresql.Driver
        ports:
         - "80:80"
